// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:spag/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: WEB_FIREBASE_API_KEY,
    appId: '1:836565681222:web:ed0c696010f615f2bd3647',
    messagingSenderId: '836565681222',
    projectId: 'spag-uo265314',
    authDomain: 'spag-uo265314.firebaseapp.com',
    storageBucket: 'spag-uo265314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ANDROID_FIREBASE_API_KEY,
    appId: '1:836565681222:android:1958ef29d97086e1bd3647',
    messagingSenderId: '836565681222',
    projectId: 'spag-uo265314',
    storageBucket: 'spag-uo265314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: IOS_FIREBASE_API_KEY,
    appId: '1:836565681222:ios:f11a70ac40948026bd3647',
    messagingSenderId: '836565681222',
    projectId: 'spag-uo265314',
    storageBucket: 'spag-uo265314.appspot.com',
    iosBundleId: 'com.example.spag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: MACOS_FIREBASE_API_KEY,
    appId: '1:836565681222:ios:d8c7647df3129a2abd3647',
    messagingSenderId: '836565681222',
    projectId: 'spag-uo265314',
    storageBucket: 'spag-uo265314.appspot.com',
    iosBundleId: 'com.example.spag.RunnerTests',
  );
}
